#!/usr/bin/env python3
"""
index_horse.py — Auto-generate transcript/update index markdown for a horse.

Scans _assets/horses/{slug}/transcripts/ and investor-updates/ and generates
index markdown files in 01_evolution/horses/{slug}/.

Usage:
    python tools/index_horse.py prudentia
"""

import re
import sys
from datetime import datetime
from pathlib import Path

EVOLUTION = Path(__file__).resolve().parent.parent
ASSETS = EVOLUTION.parent / "_assets" / "horses"


def extract_date(filename: str):
    """Try to extract a date from a filename."""
    # YYYY-MM-DD
    m = re.search(r"(\d{4})-(\d{2})-(\d{2})", filename)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"
    # DD-MMM-YYYY (e.g. 27May2026)
    m = re.search(r"(\d{1,2})([A-Z][a-z]{2})(\d{4})", filename)
    if m:
        return f"{m.group(3)}-{m.group(2)}-{m.group(1).zfill(2)}"
    # DD-MMM-YY (e.g. 02Jan26)
    m = re.search(r"(\d{1,2})([A-Z][a-z]{2})(\d{2})", filename)
    if m:
        return f"20{m.group(3)}-{m.group(2)}-{m.group(1).zfill(2)}"
    return "?"


def generate_transcripts_index(slug: str, horse_dir: Path, asset_dir: Path):
    """Generate transcripts.md from _assets/horses/{slug}/transcripts/"""
    transcripts_dir = asset_dir / "transcripts"
    if not transcripts_dir.exists():
        return

    files = sorted([f for f in transcripts_dir.iterdir() if f.is_file() and f.name != ".gitkeep"], key=lambda f: f.name)
    if not files:
        return

    lines = [
        "<!-- AUTO-GENERATED by tools/index_horse.py — do not edit manually -->",
        "---",
        f"slug: {slug}-transcripts",
        "type: transcript-index",
        f"horse: {slug}",
        f"updated_at: {datetime.now().strftime('%Y-%m-%d')}",
        "---",
        "",
        f"# {slug.replace('-', ' ').title()} — Transcript Index",
        "",
        f"## Transcripts (stored in `_assets/horses/{slug}/transcripts/`)",
        "",
        "| Date | File |",
        "|------|------|",
    ]
    for f in files:
        date = extract_date(f.name)
        lines.append(f"| {date} | `{f.name}` |")

    output = horse_dir / "transcripts.md"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"✅ Generated {output.relative_to(EVOLUTION)} ({len(files)} transcripts)")


def generate_updates_index(slug: str, horse_dir: Path, asset_dir: Path):
    """Generate investor-updates.md from _assets/horses/{slug}/investor-updates/"""
    updates_dir = asset_dir / "investor-updates"
    if not updates_dir.exists():
        return

    files = sorted([f for f in updates_dir.iterdir() if f.is_file() and f.name != ".gitkeep" and f.name != "README.md"], key=lambda f: f.name)
    if not files:
        return

    lines = [
        "<!-- AUTO-GENERATED by tools/index_horse.py — do not edit manually -->",
        "---",
        f"slug: {slug}-investor-updates",
        "type: update-index",
        f"horse: {slug}",
        f"updated_at: {datetime.now().strftime('%Y-%m-%d')}",
        "---",
        "",
        f"# {slug.replace('-', ' ').title()} — Investor Updates Index",
        "",
        f"## Updates (stored in `_assets/horses/{slug}/investor-updates/`)",
        "",
        "| Date | File |",
        "|------|------|",
    ]
    for f in files:
        date = extract_date(f.name)
        lines.append(f"| {date} | `{f.name}` |")

    output = horse_dir / "investor-updates.md"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"✅ Generated {output.relative_to(EVOLUTION)} ({len(files)} updates)")


def main():
    if len(sys.argv) < 2:
        print("Usage: python tools/index_horse.py <slug>")
        sys.exit(1)

    slug = sys.argv[1]
    horse_dir = EVOLUTION / "horses" / slug
    asset_dir = ASSETS / slug

    if not horse_dir.exists():
        print(f"❌ Horse '{slug}' not found in knowledge repo")
        sys.exit(1)

    generate_transcripts_index(slug, horse_dir, asset_dir)
    generate_updates_index(slug, horse_dir, asset_dir)


if __name__ == "__main__":
    main()